Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,7 +12,7 @@ jobs:
           tar -xzf jmeter.tgz
       - name: Run JMeter Test
         run: |
-          ./apache-jmeter-5.5/bin/jmeter -n -t Palate_App.jmx -l result.jtl
+          ./apache-jmeter-5.5/bin/jmeter -n -t Palate_App.jmx -l result.jtl > jmeter_output.log
       - name: Convert JTL to CSV
         run: |
           sed -e 's/<[^>]*>//g' result.jtl > result.csv
@@ -28,12 +28,14 @@ jobs:
           path: result.csv
       - name: Check Result Errors
         run: |
-          summary=$(echo "${{ steps.jmeter.outputs.output }}" | grep -o "summary +.*")
-          no_error_count=$(echo "$summary" | grep -o "Err:     0 (0.00%)")
-          if [ $no_error_count ]; then
-            echo "No errors found in the JMeter result"
-          else
-            echo "There were errors in the JMeter result"
-            exit 1
-          fi
+          jmeter_output=$(cat jmeter_output.log)
+          summary=$(echo "$jmeter_output" | grep -o "summary +.*")
+          while IFS = read -r line; do
+            error_count=$(echo "$line" | grep -o "Err: *[0-9]*" | awk -F' ' '{print $NF}')
+            if [ "$error_count" -gt 0 ]; then
+              echo "There were errors in the JMeter result"
+              exit 1
+            fi
+          done <<< "$summary"
+          echo "No errors found in the JMeter result"
       
